name: tagpr
on:
  push:
    branches: ["main"]
jobs:
  tagpr:
    runs-on: ubuntu-latest
    outputs:
      tagpr_tag: ${{ steps.tagpr.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
      - uses: Songmu/tagpr@v1
        id: tagpr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: echo
        run: echo ${{ steps.tagpr.outputs.tag }}

  update-version:
    if: "needs.tagpr.outputs.tagpr_tag != ''"
    runs-on: ubuntu-latest
    needs:
      - tagpr
    steps:
      - uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-edit
        run: cargo install cargo-edit
      - uses: Swatinem/rust-cache@v2
      - name: Run cargo set-version
        run: |
          set -ex
          tag=${{ needs.tagpr.outputs.tagpr_tag }}
          version=$(echo ${tag} | sed -e "s/v//")
          if [ $(yq e ".package.version" Cargo.toml) != "${version}" ]; then
            cargo set-version ${version}
            git config --local user.email github-actions[bot]@users.noreply.github.com
            git config --local user.name github-actions[bot]
            git diff
            git add Cargo.toml
            git commit -m "tagpr: Update version"
          else
            echo "Skipped"
          fi

  build-and-upload:
    if: "needs.tagpr.outputs.tagpr_tag != ''"
    runs-on: ubuntu-latest
    needs:
      - tagpr
      - update-version
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/release
        with:
          tag: ${{ steps.tagpr.outputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
