name: tagpr
on:
  push:
    branches: ["main"]
jobs:
  tagpr:
    runs-on: ubuntu-latest
    outputs:
      tagpr_tag: steps.tagpr.outputs.tag
    steps:
      - uses: actions/checkout@v4
      - uses: Songmu/tagpr@v1
        id: tagpr
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: echo
        run: echo ${{ steps.tagpr.outputs.tag }}

  build-and-upload:
    runs-on: ubuntu-latest
    needs:
      - tagpr
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/release
        with:
          tag: ${{ steps.tagpr.outputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
        if: "needs.tagpr.outputs.tagpr_tag != ''"
